In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("Global Superstore.csv")

In [5]:
df.shape

(51290, 27)

In [8]:
df.head()

,Category,City,Country,Customer ID,Customer Name,Discount,Market,ji_lu-shu,Order Date,Order ID,...,Sales,Segment,Ship Date,Ship Mode,Shipping Cost,State,Sub-Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,00:00.0,CA-2011-130813,...,19,Consumer,00:00.0,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,00:00.0,CA-2011-148614,...,19,Consumer,00:00.0,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,00:00.0,CA-2011-118962,...,21,Consumer,00:00.0,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,00:00.0,CA-2011-118962,...,111,Consumer,00:00.0,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,00:00.0,CA-2011-146969,...,6,Consumer,00:00.0,Standard Class,1.32,California,Paper,2011,North America,40

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  str
 1   City            51290 non-null  str
 2   Country         51290 non-null  str
 3   Customer ID     51290 non-null  str
 4   Customer Name   51290 non-null  str
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  str
 7   ji_lu-shu       51290 non-null  int64
 8   Order Date      51290 non-null  str
 9   Order ID        51290 non-null  str
 10  Order Priority  51290 non-null  str
 11  Product ID      51290 non-null  str
 12  Product Name    51290 non-null  str
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  str
 16  Row ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  str
 19  Ship Date       51290 non-null  str
 20  Ship Mode       51290 non-null  str
 21  Shipping Cost   51290 non-null  float64
 22  State           51290 non-null  str
 23  Sub-Category    51290 non-null  str
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  str
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), str(18)
memory usage: 10.6 MB

In [10]:
df.isnull().sum()

Category          0
City              0
Country           0
Customer ID       0
Customer Name     0
Discount          0
Market            0
ji_lu-shu         0
Order Date        0
Order ID          0
Order Priority    0
Product ID        0
Product Name      0
Profit            0
Quantity          0
Region            0
Row ID            0
Sales             0
Segment           0
Ship Date         0
Ship Mode         0
Shipping Cost     0
State             0
Sub-Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [11]:
df['ji_lu-shu'].unique()

array([1])

In [12]:
df = df.drop(columns=['ji_lu-shu'])

In [13]:
df.columns

Index(['Category', 'City', 'Country', 'Customer ID', 'Customer Name',
       'Discount', 'Market', 'Order Date', 'Order ID', 'Order Priority',
       'Product ID', 'Product Name', 'Profit', 'Quantity', 'Region', 'Row ID',
       'Sales', 'Segment', 'Ship Date', 'Ship Mode', 'Shipping Cost', 'State',
       'Sub-Category', 'Year', 'Market2', 'weeknum'],
      dtype='str')

In [14]:
df['Order Date'].head()

0    00:00.0
1    00:00.0
2    00:00.0
3    00:00.0
4    00:00.0
Name: Order Date, dtype: str

In [15]:
df = df.drop(columns=['Order Date', 'Ship Date'])

In [16]:
df.columns

Index(['Category', 'City', 'Country', 'Customer ID', 'Customer Name',
       'Discount', 'Market', 'Order ID', 'Order Priority', 'Product ID',
       'Product Name', 'Profit', 'Quantity', 'Region', 'Row ID', 'Sales',
       'Segment', 'Ship Mode', 'Shipping Cost', 'State', 'Sub-Category',
       'Year', 'Market2', 'weeknum'],
      dtype='str')

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df[['Sales', 'Profit', 'Discount', 'Shipping Cost']].describe()

              Sales        Profit      Discount  Shipping Cost
count  51290.000000  51290.000000  51290.000000   51290.000000
mean     246.498440     28.610982      0.142908      26.375818
std      487.567175    174.340972      0.212280      57.296810
min        0.000000  -6599.978000      0.000000       0.002000
25%       31.000000      0.000000      0.000000       2.610000
50%       85.000000      9.240000      0.000000       7.790000
75%      251.000000     36.810000      0.200000      24.450000
max    22638.000000   8399.976000      0.850000     933.570000

In [19]:
df[df['Sales'] == 0]

,Category,City,Country,Customer ID,Customer Name,Discount,Market,Order ID,Order Priority,Product ID,...,Row ID,Sales,Segment,Ship Mode,Shipping Cost,State,Sub-Category,Year,Market2,weeknum
46158,Office Supplies,Houston,United States,ZC-219104,Zuschuss Carroll,0.8,US,US-2014-102288,Medium,OFF-AP-10002906,...,35398,0,Consumer,Standard Class,0.01,Texas,Appliances,2014,North America,25

In [21]:
df.to_csv("Global_Superstore_clean.csv", index=False)